### ISSUE TITLE
Landscape mode shows no clock 


### ISSUE THREAD

**Issue by ASUFLEXGITHUB** [dfyockey/RomanDigital#13]
Putting my phone in landscape shows a blank screen.
Putting it back in portrait shows a clock.
Not sure if it's device specific.

Device: Samsung Galaxy A12
One Ui 5.1 Core
Android 13

https://github.com/user-attachments/assets/6514a2fe-d6b6-4652-9b7f-5d8143975d0d

**Comment by ASUFLEXGITHUB** [comment]
Note: Changing the font to default actaully makes the clock show the time in landscape. So this bug is also tied to the Rosemary font issue.

**Comment by dfyockey** [comment]
Thanks for checking on that. There's no problem showing in landscape in testing with Rosemary on Android 14 with One UI 6.1, so it may be related to One UI 5.1 or (less likely) Android 13.

**Comment by dfyockey** [comment]
@ASUFLEXGITHUB New release v1.1.2 is a fix for the clock text size problem (Issue #14). Assuming you update, please post whether or not it has any effect on this landscape issue. TIA

**Comment by ASUFLEXGITHUB** [comment]
Just updated and the bug is gone! The clock is visible in landcsape. 
Thanks alot!
