### ISSUE TITLE
Clock text is too large

### ISSUE THREAD

**Issue by ASUFLEXGITHUB** [dfyockey/RomanDigital#14]
The clock text is too large that it cuts off my screen.
Also, setting it to align to divider makes it worse.

Device: Samsung Galaxy A12
One Ui 5.1 Core
Android 13

The time is 10:38 am but it shows X:XXX instead of X:XXXVIII
 ![Screenshot_20241018_103831_RomanDigital.jpg](https://github.com/user-attachments/assets/b02b0679-11a5-4b11-95b2-753e3e202ab5)

**Comment by dfyockey** [comment]
Looks like you're using Samsung's Rosemary font, which is variable width. Haven't yet provided for use of variable-width fonts. In the short term, my aim will be for modification to insure that either a monospace font is used for the app display regardless of the system-wide setting, or that the font size is calculated to be small enough to fit even if the fit is less-than-perfect, i.e. there's excess space at the ends.
